platform :ios, '13.0'

target 'App' do
  use_frameworks!
  use_modular_headers!

  # Pods for App
  pod 'Capacitor', :path => '../node_modules/@capacitor/core'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/cordova'
  pod 'CapacitorCommunityBluetoothLE', :path => '../node_modules/capacitor-community-bluetooth-le'
  pod 'CapacitorCommunityPushNotifications', :path => '../node_modules/capacitor-community-push-notifications'

  # Add other pods here
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end